# Trial Settings
trialNumber: 10
trialLearningRate: [0.0001, 0.1]
trialOptimizer: ["Adam", "SGD"]
trialBackbone: ["resnet18", "resnet34", "resnet50", "resnet101", "resnet152"]
trialMomentum: [0.1, 0.99]

configFile: secrets.ini
imagePath: src/Data/Images
informationCSV: src/Data/TrainGenderInformation.csv
validationImagePath: src/Data/ImagesValidation
validationInformationCSV: src/Data/ValidationGenderInformation.csv

device: cuda:0
numEpochs: 2
accuracyThreshold: 0.01
pretrained: true
lossFunction: BCEWithLogitsLoss
savePath: Checkpoints
logInterval: 0.1
momentum: 0.9

numberClass: 2
seed: 42
batchSize: 2
imageSize: 32
numWorkers: 4 
testSize: 0.05