name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize actions
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install torch==1.11.0 torchvision==0.12.0

      - name: PyTest for training classes
        run: pytest

      - name: Docker install test for environment
        run: |
          docker build -t train .